name: CI
on: push 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - name: Deploy
       env:
         PASSWORD: ${{ secrets.MY_PASSWORD }}
       run: |
         echo "Deploying with token length: ${#PASSWORD}
